### ISSUE TITLE
PassportCard component action name too generic for screen reader

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-accessibility-passport#116]
From AAACT:

> Associating the links that read “view passport” with the names, is not easy for the screen reader user. View whose passport? Besides, all 3 have the same name with different destinations.
> Screenshot:
> 
> One solution could be placing the name and the link in the same p element.

### Screenshot
![image.png](https://images.zenhubusercontent.com/5f7b33373ac7b7279de9a3c5/3c9cf8f2-cf11-4971-bb05-34a5bd2ab399)

**Comment by JoshBeveridge** [comment]
So there are a couple of options here:
- we add a span between "view" and "passport" that is set to `data-h2-visibility="b(invisible)"` that contains the user's name, so that screen readers read the label as "View Frank Turot's passport"
- we use an `aria-label` to provide extra context
- we change the visible label to simply read "View Frank Turot's passport"

I'd argue that the visual association of the card is enough for sighted users to understand the relationship between the link and the owner of the passport, so my gut tells me that the first option is the least invasive while having the most impact for the problem described. We'll want to test this implementation with a screen reader before labelling it as complete.

**Comment by mnigh** [comment]
@gobyrne chooses:

- we change the visible label to simply read "View Frank Turot's passport"
