### ISSUE TITLE
English Updates resulting from Comparative Language Verification

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-accessibility-passport#172]

**Comment by RM-1978** [comment]
@mnigh Many thanks for taking the time to review the challenges that this might pose to existing strings :) As promised, please find the two Word versions of the strings with the changes highlighted. 

June 3: 
[https://app.zenhub.com/files/477804994/be7c4f05-2978-44d5-a1bb-ca19780cff39/download](https://app.zenhub.com/files/477804994/be7c4f05-2978-44d5-a1bb-ca19780cff39/download)

June 4: 
[https://app.zenhub.com/files/477804994/ca5e9f24-f8e2-49ae-9f6b-de4603b39a94/download](https://app.zenhub.com/files/477804994/ca5e9f24-f8e2-49ae-9f6b-de4603b39a94/download)

**Comment by mnigh** [comment]
# Document 1 (June 3)
## Notes
### 1. "AZxfMW": "Share with someone new", *** should it say “Share with another individual/ person”?

This is a copy change, I will leave the decision up to you @RM-1978.

### 2. "ECkqWQ": "Below is a solution(s) to the Noise in the workplace barrier. Review and action the solution and indicate its status.", *** Is it up to the manager to select the solution, what if they pick the least expensive one, just because it costs less, what if they pick the least functional one for the employee, I know this is not the place to make this comment and I believe I have made it when I reviewed other versions but it is an important one to address.: Changed in Text file

This seems related to the planning of how the application is meant to work, could you speak to this please @gobyrne? If required, please create a new issue, thanks.

### 3. "keHh9P": "My manager information", *** why do we alternate between “my” and “your”? Also why sometimes “manager’s” and sometimes “manager”?

I am not sure @RM-1978, I did not write the copy. If there are particular instances of copy you want changed though, please identify them and what you would like them to be changed to in a new issue, thanks.

### 4. "sFMRpq": "Emergency documentation",  *** what is “emergency documentation”? 

_Emergency documentation_ is a heading for a list of files that ostensibly a passport owner would upload. See screenshot:
![Screen Shot 2022-06-06 at 16 23 31](https://user-images.githubusercontent.com/3046459/172242613-68d4e41e-0286-4622-8840-9d50a825b0a7.png)
Does that information and screenshot provide enough context to answer your question, @RM-1978?

**Comment by RM-1978** [comment]
Hi @mnigh , 

Thanks for your note. 

For items 1 to 3: Please see the decisions I have already made on these pieces of the copy here: 
[English text Passport Soln June 3.txt](https://github.com/GCTC-NTGC/gc-accessibility-passport/files/8847833/English.text.Passport.Soln.June.3.txt)

For Item 4: Please just remove this feature, unless @JoshBeveridge or @gobyrne  see value in allowing the user to upload potentially protected information.

**Comment by JoshBeveridge** [comment]
We included it in the original design as it was requested by OPSA - if we can remove it now, let's do so.

**Comment by mnigh** [comment]
> _Emergency documentation_ is a heading for a list of files that ostensibly a passport owner would upload. See screenshot:

An issue has been created for removing the emergency documentation section:

- https://github.com/GCTC-NTGC/gc-accessibility-passport/issues/175
